"""
Nmap XML output parser.

Converts raw Nmap XML (as produced by app.services.nmap_service.run_nmap_scan)
into normalized, structured Python objects. This module performs NO
inference: every field returned here is taken directly from Nmap's own
output. It never guesses, estimates, or fabricates ports, services, or OS
matches that Nmap itself did not report.

Trust note: the XML parsed here is generated by the Nmap binary this
application invoked itself (not arbitrary attacker-supplied XML), so the
standard library xml.etree.ElementTree is used. If this parser is ever
repurposed to accept XML from an untrusted source, a hardened parser
(e.g. defusedxml) should be used instead.
"""

import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from typing import List, Optional

from app.core.exceptions import NmapParsingError


@dataclass
class ParsedPortService:
    port_number: int
    protocol: str
    state: str
    service_name: Optional[str] = None
    product: Optional[str] = None
    version: Optional[str] = None
    extra_info: Optional[str] = None


@dataclass
class ParsedHost:
    ip_address: str
    status: str
    hostname: Optional[str] = None
    mac_address: Optional[str] = None
    os_name: Optional[str] = None
    os_accuracy: Optional[int] = None
    ports: List[ParsedPortService] = field(default_factory=list)


def parse_nmap_xml(xml_output: str) -> List[ParsedHost]:
    """Parse Nmap XML output into a list of ParsedHost objects.

    Raises NmapParsingError if the XML is malformed or missing the
    expected root structure.
    """
    try:
        root = ET.fromstring(xml_output)
    except ET.ParseError as exc:
        raise NmapParsingError(f"Nmap XML output could not be parsed: {exc}") from exc

    if root.tag != "nmaprun":
        raise NmapParsingError(
            f"Unexpected Nmap XML root element: '{root.tag}' (expected 'nmaprun')"
        )

    parsed_hosts: List[ParsedHost] = []

    for host_elem in root.findall("host"):
        parsed_host = _parse_host(host_elem)
        if parsed_host is not None:
            parsed_hosts.append(parsed_host)

    return parsed_hosts


def _parse_host(host_elem: ET.Element) -> Optional[ParsedHost]:
    status_elem = host_elem.find("status")
    status = status_elem.get("state") if status_elem is not None else "unknown"

    ipv4_addr = None
    mac_addr = None
    for addr_elem in host_elem.findall("address"):
        addr_type = addr_elem.get("addrtype")
        if addr_type == "ipv4" and ipv4_addr is None:
            ipv4_addr = addr_elem.get("addr")
        elif addr_type == "mac" and mac_addr is None:
            mac_addr = addr_elem.get("addr")

    if not ipv4_addr:
        # A host entry without a resolvable IPv4 address carries no
        # actionable evidence for this platform; skip it rather than
        # fabricate a placeholder address.
        return None

    hostname = None
    hostnames_elem = host_elem.find("hostnames")
    if hostnames_elem is not None:
        hostname_elem = hostnames_elem.find("hostname")
        if hostname_elem is not None:
            hostname = hostname_elem.get("name")

    os_name = None
    os_accuracy = None
    os_elem = host_elem.find("os")
    if os_elem is not None:
        best_match = None
        best_accuracy = -1
        for osmatch_elem in os_elem.findall("osmatch"):
            try:
                accuracy = int(osmatch_elem.get("accuracy", "0"))
            except ValueError:
                accuracy = 0
            if accuracy > best_accuracy:
                best_accuracy = accuracy
                best_match = osmatch_elem
        if best_match is not None:
            os_name = best_match.get("name")
            os_accuracy = best_accuracy

    ports: List[ParsedPortService] = []
    ports_elem = host_elem.find("ports")
    if ports_elem is not None:
        for port_elem in ports_elem.findall("port"):
            parsed_port = _parse_port(port_elem)
            if parsed_port is not None:
                ports.append(parsed_port)

    return ParsedHost(
        ip_address=ipv4_addr,
        status=status or "unknown",
        hostname=hostname,
        mac_address=mac_addr,
        os_name=os_name,
        os_accuracy=os_accuracy,
        ports=ports,
    )


def _parse_port(port_elem: ET.Element) -> Optional[ParsedPortService]:
    port_id_raw = port_elem.get("portid")
    protocol = port_elem.get("protocol")
    if port_id_raw is None or protocol is None:
        return None

    try:
        port_number = int(port_id_raw)
    except ValueError:
        return None

    state_elem = port_elem.find("state")
    state = state_elem.get("state") if state_elem is not None else "unknown"

    service_name = None
    product = None
    version = None
    extra_info = None
    service_elem = port_elem.find("service")
    if service_elem is not None:
        service_name = service_elem.get("name")
        product = service_elem.get("product")
        version = service_elem.get("version")
        extra_info = service_elem.get("extrainfo")

    return ParsedPortService(
        port_number=port_number,
        protocol=protocol,
        state=state or "unknown",
        service_name=service_name,
        product=product,
        version=version,
        extra_info=extra_info,
    )